model:
  num_encoder_layers: 2
  num_decoder_layers: 2
  embedding_meta:
    pos:
      mode: learned
      emb_num: 16
      over_boxes: True
    temp: 
      mode: "off"
dataset:
  train_dataset:
    slp_files: ['190612_110405_wt_18159111_rig2.2@11730.slp']
    video_files: ['190612_110405_wt_18159111_rig2.2@11730.mp4']
    clip_length: 16
