ckpt_path: null

tracker:
  overlap_thresh: 0.01
  decay_time: null
  iou: "mult"
  max_tracks: 2
  max_center_dist: null
  persistent_tracking: true

dataset:
  test_dataset:
    dir:
      path: null
      labels_suffix: ".slp"
      vid_suffix: ".mp4"
    chunk: true
    clip_length: 32
    anchors: "centroid"

dataloader:
  test_dataloader:
    shuffle: false
    num_workers: 0

trainer:
  limit_test_batches: 1.0

save_frame_meta: false
outdir: "./results"
